name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OCPD_SIGN_KEY: ${{ secrets.OCPD_SIGN_KEY }}
          OCPD_SIGN_KEY_ID: ${{ secrets.OCPD_SIGN_KEY_ID }}
          OCPD_SIGN_PASSPHRASE: ${{ secrets.OCPD_SIGN_PASSPHRASE }}
